/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /workspace/diffusion-llms/models/classifier/checkpoints exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name     | Type            | Params | Mode
-----------------------------------------------------
0 | backbone | LladaBackbone   | 8.0 B  | train
1 | model    | LLaDaClassifier | 4.1 K  | train
-----------------------------------------------------
518 M     Trainable params
7.5 B     Non-trainable params
8.0 B     Total params
32,062.341Total estimated model params size (MB)
3         Modules in train mode
422       Modules in eval mode
Epoch 0:   2%|â–ˆ                                                               | 58/3385 [00:17<17:07,  3.24it/s, v_num=nzky, train/loss=0.224, train/acc=0.702]
/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=223` in the `DataLoader` to improve performance.
/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=223` in the `DataLoader` to improve performance.

Detected KeyboardInterrupt, attempting graceful shutdown ...
